# Jekyll configuration

name: RayHightower.com
description: Software Developer. Tech company founder.

# Url is currently only used only for the RSS feed in feed.xml
# url: /
url: http://localhost:4001

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
# baseurl: http://localhost:4001
baseurl: /

# excerpt generation
excerpt_link: "Continue reading &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: rayhightower
  twitter: rayhightower
  stackoverflow:
  linkedin: http://linkedin.com/in/rayhightower
  instagram:
  lastfm:
  rss: feed.xml

# Google Analytics key, leave blank to ignore
# google_analytics_key: UA-330946-28
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: rayhightower
comments: true

# permalink: /:year/:month/:title
permalink: /blog/:year/:month/:day/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
